import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Home from "./page";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Soporte Tesis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={outfit.className}>
        {children}
        <Home></Home>
      </body>
    </html>
  );
}
